services:
    api:
        container_name: anon_nginx
        build:
            context: ./
            dockerfile: docker/development/nginx/Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - anonchat-network
    api-php-fpm:
        container_name: anon_api-php
        build:
            context: ./
            dockerfile: docker/development/php-fpm/Dockerfile
        volumes:
            - .:/var/www
        networks:
            - anonchat-network
        depends_on:
            - mysql
            - api
        healthcheck:
            test: ["CMD-SHELL", "test -f /tmp/.ready && php artisan about"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 30s
    anonymous-chat:
        container_name: anonymous-chat
        build:
            context: ./
            dockerfile: node-server/anonymous/Dockerfile
            args:
                - ANONYMOUS_PORT=${ANONYMOUS_PORT:-8005}
        environment:
            - ANONYMOUS_PORT=${ANONYMOUS_PORT:-8005}
        ports:
            - "${ANONYMOUS_PORT:-8005}:${ANONYMOUS_PORT:-8005}"
        networks:
            - anonchat-network 
        depends_on:
            - redis
    persistent-chat:
        container_name: persistent-chat
        build:
            context: ./
            dockerfile: node-server/chats_server/Dockerfile
            args:
                - CHATS_PORT=${CHATS_PORT:-8006}
        environment:
            - CHATS_PORT=${CHATS_PORT:-8006}
        ports:
            - "${CHATS_PORT:-8006}:${CHATS_PORT:-8006}"
        networks:
            - anonchat-network 
        depends_on:
            - redis
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: anon_db
        ports:
            - '${FORWARD_DB_PORT:-3307}:3307'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1\
            MYSQLD_OPTS: "--skip-networking --socket=/tmp/mysql.sock"
        volumes:
            - dbdata:/var/lib/mysql
            # - ./docker/my.cnf:/etc/mysql/my.cnf
        networks:
            - anonchat-network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: redis:latest
        container_name: anon_redis
        restart: always
        ports:
        - "${REDIS_PORT:-6380}:6380"
        volumes:
        - redis_data:/data
        environment:
            - ALLOW_EMPTY_PASSWORD=no
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        networks:
            - anonchat-network 
volumes:
    cache_data:
        driver: "local"
    dbdata:
        driver: "local"
    redis_data:
        driver: "local"
networks:
    anonchat-network:
        driver: bridge